version: '3'

services:
  orleansdomo.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  orleans.web:
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

